CLASS_NAME = ['adho mukha svanasana', 'adho mukha vriksasana',
                    'ananda balasana', 'anantasana', 'anjaneyasana',
                    'ardha chandrasana', 'ardha matsyendrasana', 'ardha pincha mayurasana',
                    'ardha uttanasana', 'astavakrasana', 'baddha konasana',
                    'bakasana','balasana', 'bhujangasana', 'bhujapidasana',
                    'bitilasana', 'camatkarasana','chaturanga dandasana', 'dandasana',
                    'dhanurasana', 'dwi pada viparita dandasana','eka pada koundinyanasana',
                    'eka pada rajakapotasana', 'garudasana', 'gomukhasana',
                    'halasana', 'janu sirsasana', 'kapotasana', 'krounchasana', 'kurmasana',
                    'malasana', 'marjaryasana', 'matsyasana', 'mayurasana', 'natarajasana',
                    'parighasana', 'paripurna navasana', 'parivrtta janu sirsasana',
                    'parivrtta parsvakonasana','parivrtta trikonasana', 'parsva bakasana',
                    'parsvottanasana', 'paschimottanasana','pincha mayurasana',
                    'prasarita padottanasana', 'purvottanasana', 'salabhasana',
                    'salamba sarvangasana', 'salamba sirsasana', 'savasana',
                    'setu bandha sarvangasana','supta padangusthasana', 'supta virasana',
                    'tittibhasana', 'tolasana', 'upavistha konasana',
                    'urdhva prasarita eka padasana', 'ustrasana', 'utkatasana',
                    'uttana shishosana', 'uttanasana','utthita hasta padangustasana',
                    'vajrasana', 'vasisthasana', 'viparita karani', 'virabhadrasana i',
                    'virabhadrasana ii', 'virabhadrasana iii', 'vriksasana', 'vrischikasana',
                    'yoganidrasana']